apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinebookstore
spec:
  selector:
      matchLabels:
        app: onlinebookstore
  replicas: 1
  template:
      metadata:
        labels:
            app: onlinebookstore
      spec:
        containers:
        - name: onlinebookstore
          image:  myregistrydemo1.azurecr.io/image1:20221021.16
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /
          livenessProbe:
            httpGet:
              port: 8080
              path: /
          
---
apiVersion: v1
kind: Service
metadata:
  name: onlinebookstore
spec:
  type: LoadBalancer
  selector:
    app: onlinebookstore
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
