apiVersion : apps/v1
kind: Deployment
metadata:
  name: image2 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image2
  template:
    metadata:
      labels:
        app: image2 
    spec:
      containers:
        - name: image2 
          image: myregistrydemo1.azurecr.io/image2
          ports:
          - containerPort: 8080