apiVersion : apps/v1
kind: Deployment
metadata:
  name: onlinebookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlinebookstore
  template:
    metadata:
      labels:
        app: onlinebookstore 
    spec:
      containers:
        - name: onlinebookstore 
          image: myregistrydemo1.azurecr.io/onlinebookstore
          ports:
          - containerPort: 8080
